<?php
/**
 * @file
 * Code for the open_hourglass_config feature.
 */

include_once 'open_hourglass_config.features.inc';

// @todo: we are putting field settings image field manually to a FID, we need to be able to find a way to update the field settings

/**
 * Implements hook_menu.
 */
function open_hourglass_config_menu() {
  $items['admin/config/system/ourly'] = array(
    'title' => 'Our.ly Configuration',
    'position' => 'right',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ourly_config_settings'),
    'access arguments' => array('administer ourly'),
    'description' => 'Allow various site configuration settings',
    'file' => 'open_hourglass_config.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_theme.
 */
function open_hourglass_config_theme() {
  return array(
    'ourly_settings_menu' => array(),
  );
}

/**
 * Implements hook_permission().
 */
function open_hourglass_config_permission() {
  return array(
    'administer ourly' => array(
      'title' => t('Administer ourly'),
      'description' => t('Perform configuration options for Our.ly distribution'))
  );
}

/**
 * Implements hook_menu_alter
 */
function open_hourglass_config_menu_alter(&$items) {
  // setting the user edit page as the default user page
  // we do not need a user view page
  unset($items['user/%user/view']);
  $items['user/%user/edit']['type'] = MENU_DEFAULT_LOCAL_TASK;
  $items['user/%user']['page callback'] = '_open_hourglass_config_menu_user';
  $items['user/%user']['page arguments'] = array(1);

  // Making the title more friendly
  $items['admin/structure/taxonomy/%taxonomy_vocabulary_machine_name/add']['title callback'] = 'open_hourglass_term_add_title';
  $items['admin/structure/taxonomy/%taxonomy_vocabulary_machine_name/add']['title arguments'] = array(3);

}

/**
 * Preprocess user login page
 * @param $vars
 */
function open_hourglass_config_preprocess_page(&$vars) {
  $vars['settings_nav'] = theme('ourly_settings_menu');
}

/**
 * Implements hook_user_presave
 * @param $edit
 * @param $account
 * @param $category
 */
function open_hourglass_config_user_presave(&$edit, $account, $category) {
  if (array_key_exists('field_user_name', $edit)) {
    $edit['data']['name'] = $edit['field_user_name'];
  }
}

/**
 * Implements hook_node_presave
 * @param $node
 */
function open_hourglass_config_node_presave($node) {
  if ($node->type !== 'project') {
    return;
  }

  $query = new EntityFieldQuery();

  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'project')
    ->propertyCondition('status', NODE_PUBLISHED)
    ->propertyCondition('promote', 1);

  $result = $query->execute();

  if (empty($result)) {
    return;
  }
  foreach ($result['node'] as $_node) {
    if($_node->nid == $node->nid) {
      continue;
    }
    $nodeItem = node_load($_node->nid);
    $nodeItem->promote = 0;
    node_save($nodeItem);
  }
}

/**
 * @param $vocabulary
 * @return null|string
 */
function open_hourglass_term_add_title($vocabulary) {
  return t('Add @title', array('@title' => $vocabulary->name));
}

function _open_hourglass_config_menu_user($account) {
  drupal_goto('user/' . $account->uid . '/edit');
}

// @todo Use frontpage module for a better implementation
/**
 * Implements hook_init
 */
function open_hourglass_config_init() {
  // redirect anonymous user to login page, this whole site should be locked down for anonymous users
  global $user;
  if ($user->uid === 0) {
    if (arg(0) != 'user') {
      drupal_goto('user/login');
    }
  }
}

/**
 *  Implements hook_custom_theme
 */
function open_hourglass_custom_theme() {
  // setting the user pages to use the our theme
  if (arg(0) == 'user') {
    return 'ourly';
  }
}

/**
 * Implements hook_user_login
 * @param $edit
 * @param $account
 */
function open_hourglass_config_user_login(&$edit, $account) {
  // redirect user after login to the home page
  $front_page = variable_get('site_frontpage', 'node');
  $edit['redirect'] = $front_page;
}

/**
 * Implements hook_form_FORM_ID_alter
 */
function open_hourglass_config_form_time_entry_node_form_alter(&$form, &$form_state, $form_id) {
	// adding custom form validation for time entry node form
	$form['#validate'][] = 'open_hourglass_config_time_entry_validate';
}

/**
 * Custom validation callback
 */
function open_hourglass_config_time_entry_validate($form, &$form_state) {
	$lang = $form_state['values']['language'];
	$time_spent = $form_state['values']['field_time_entry_time_spent'][$lang][0]['value'];

  if ($time_spent == 0) {
    form_set_error('field_time_entry_time_spent', t('You must enter something greater than 0'));
  }
  // make sure time entered are in the multiple of .25
	$quotient = $time_spent / .25;
	if (stristr($quotient, '.')) {
		form_set_error('field_time_entry_time_spent', t('Time spent should be made in the increment of .25'));
	}
}

/**
 * hook_form_FORM_ID_alter
 * @param $form
 * @param $form_state
 * @param $form_id
 */
function open_hourglass_config_form_menu_edit_item_alter(&$form, &$form_state, $form_id) {
  $form['bootstrap_icon'] = array(
    '#type' => 'textfield',
    '#title' => t('Icon Name'),
    '#description' => t('Enter the name of the icon from font-awesome icon list'),
    '#weight' => 1,
    '#default_value' => (array_key_exists('bootstrap_icon', $form['options']['#value'])) ? $form['options']['#value']['bootstrap_icon'] : '',
  );
  $form['#validate'][] = 'open_hourglass_config_menu_item_icon_save';
}

/**
 * Submission handler to save menu item icon
 * @param $form
 * @param $form_state
 */
function open_hourglass_config_menu_item_icon_save($form, &$form_state) {
  if (empty($form_state['values']['bootstrap_icon'])) {
    return;
  }
  $form_state['values']['options']['bootstrap_icon'] = $form_state['values']['bootstrap_icon'];
}

/**
 * Implements hook_form_alter
 * @param $form
 * @param $form_state
 * @param $form_id
 */
function open_hourglass_config_form_alter(&$form, &$form_state, $form_id) {

  if ($form['#form_id'] !== 'time_entry_node_form') {
    return;
  }

  // Default submission button redirect to home
  $form['actions']['submit']['#submit'][] = 'open_hourglass_config_save_done';

  // Adding a add and new button.
  $form['actions']['save_new'] = array(
    '#type' => 'submit',
    '#value' => t('Save and New'),
    '#submit' => array(
      'node_form_submit',
      'open_hourglass_config_save_new',
    ),
  );
}

/**
 * Redirect home.
 * @param $form
 * @param $form_state
 */
function open_hourglass_config_save_done($form, &$form_state) {
  // Redirect to home page.
  drupal_goto('<front>');
}

/**
 * Form submission handler
 * @param $form
 * @param $form_state
 */
function open_hourglass_config_save_new($form, &$form_state) {
  // Forcing redirect.
  drupal_goto('node/add/time-entry');
}

/**
 * Theming settings menu callback.
 * @return string
 */
function theme_ourly_settings_menu() {
  if (!user_access('administer ourly')) {
    return;
  }

  $sub_items = array(
    l('Our.ly Config', 'admin/config/system/ourly'),
  );
  $sub_menu = theme('item_list', array('type' => 'ul', 'attributes' => array('class' => array('dropdown-menu'),), 'items' => $sub_items));
  $sub_menu = strip_tags($sub_menu, '<ul><li><a>');

  $menu = '<li class="dropdown">
    <a href="javscript:;" class="dropdown-toggle" data-toggle="dropdown">
    <i class="icon-cog"></i>
    settings
    <b class="caret"></b>
    </a>' . $sub_menu . '
    </li>';

  return $menu;
}